language: php
php:
  - '7.3'
services:
  - mysql
sudo: required
install:
  - composer install --no-interaction
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:update --force --env=test
  - php bin/console doctrine:fixtures:load -n --env=test
script:
  - php bin/phpunit